<MyLayout>
    BoxLayout:
        orientation:'vertical'
        size :root.width,root.height

        padding:50
        spaceing:20

        Label:
            id:my_lable
            text:'The World'
            font_size:32
        Button:
            text:'Press Me!'
            font_size:32
            size_hint:.5,.5
            pos_hint:{"center_x":0.5}
            on_release: root.animate_it(self) 